### ISSUE TITLE
Keyword benign does not indicate there is no issue. integer_overflow_benign_1.sol

### ISSUE THREAD

**Issue by feliam** [EthereumAnalysisBenchmarks/ethereum-analyzer-suites-runner#32]
The comment in integer_overflow_benign_1.sol suggest the integer overflow there has no implications in any aspect of the execution so maybe it should not be a finding ?

//Single transaction overflow
//Post-transaction effect: overflow never escapes function

pragma solidity ^0.4.19;

contract Benchmark {
    uint public count = 1;

    function run(uint256 input) public {
        uint res = count - input;
    }
}

**Comment by rocky** [comment]
Yes my understanding is that because the code is equivlant to: 

```solidity
function run(uint256 input) public {
    ;
}
```

the overflow is "benign". Again, that is just my understanding and I could be wrong.

**Comment by rocky** [comment]
This has been fixed in [the 2018-08-30 01:04:41.975315 report](https://ethereumanalysisbenchmarks.github.io/Suhabe/index.html)
