### ISSUE TITLE
"benign" does not mean non-issue in integer_overflow_benign_2.sol

### ISSUE THREAD

**Issue by feliam** [EthereumAnalysisBenchmarks/ethereum-analyzer-suites-runner#33]
The comment in there suggests the int overflow wont affect any execution of the contract

//Single transaction overflow
//Post-transaction effect: overflow nevers escapes to publicly-readable storage

https://github.com/ConsenSys/evm-analyzer-benchmark-suite/tree/master/benchmarks/integer_overflow_benign_2.sol

**Comment by rocky** [comment]
Yes, I think that is correct. I think the idea is that there is a `require` in there that checks on the caller side, and a switch with a case in function `minus()` where `err` is set. 

That said, this is just my understanding and I could have this wrong. 

Down the line when we should capture this in say integer_overflow_benign_2.md in that folder.

**Comment by feliam** [comment]
ok so diff tools here should report nothing? correct? 
"True negative"?

**Comment by suhabe** [comment]
Yes, I believe ideally tools wouldn't report an overflow bug on this benchmark, even though the variable itself actually overflows. This example was derived from an actual safe math library: https://github.com/Modular-Network/ethereum-libraries/blob/master/BasicMathLib/BasicMathLib.sol

**Comment by rocky** [comment]
@vl-ti This is a logic error that seems to have gotten introduced recently when the code was expanded to handle Manticore. 

We separating "false positives" from "benign" false positives. See Issue #6

**Comment by rocky** [comment]
@feliam A couple things for the future that would help me out. 

This started as a benchmark question and wondered into a genuine bug. I would appreicate it if you'd open benchmark questions in https://github.com/ConsenSys/evm-analyzer-benchmark-suite/  (I can't move this issue across organizations or I would have done that). 

I realize we dropped the ball with respect to some questions you asked a while ago. Things have changed a little so perhaps we'll be better about that.

**Comment by feliam** [comment]
I'll try to be more clear next time. 
My point was (and kind of depended on the benchmark q) that this should be a "True negative". Green when no finding is reported.

**Comment by rocky** [comment]
For now, in https://github.com/EthereumAnalysisBenchmarks/evm-analyzer-bench-suites/pull/24 I have been treating "Benign" situations as acceptable, to see how this works out. We can change it later if need be.

I'll also note that "True Negative" is also a little bit of a wiggle word. The analyzer could be totally oblivious to any subtleties whatsoever and it would get the right answer, in the same way that a stopped clock is right twice a day. So there is some sort of honor system going on when we say "True Negative" that the analyzer really knows what it is talking about.

**Comment by vl-ti** [comment]
Ok, sounds reasonable. So, to clarify - it is planned add additional status - "Benign".

Lets discuss and implementation a bit then. Now, I see that such test cases got has_bug flag set to "benign", but usage of this field is a bit misleading, as based on its prefix it is intended to be boolean but not string. Maybe it is worth to introduce "is_benign" or just "benign" property which is False by default?

Regarding logic itself. I am thinking about what if test case is marked as benign but tool did not reported any issues?

**Comment by rocky** [comment]
> Lets discuss an implementation a bit then.

The recommendations here are great. I have something tentatively in place in master, but the implementation you describe is cleaner, so please replace it if you feel up to it.

> Regarding logic itself. I am thinking about what if test case is marked as benign but tool did not reported any issues?

As I wrote: 

> I'll also note that "True Negative" is also a little bit of a glib. The analyzer could be totally oblivious to any subtleties whatsoever and it would get the right answer, in the same way that a stopped clock is right twice a day. So there is some sort of honor system going on when we say "True Negative" that the analyzer really knows what it is talking about.

One other little thought I had was changing the shades of green for "found benign" and "false negative" to a slightly different shade that suggests these are not as clear cut.

**Comment by feliam** [comment]
I think that if occurrence or not of the "thing" you are detecting will not generate two different behaviors/traces in the code then it should not be an issue. This benign thing is odd. Proposal. Remove all the benchmarks that have that or deal with it by sending it to the normal classes. 

As for the honor system. I do not think you need to appeal to that and rather device a good benchmark test case set to uncover the stopped clock and rank better the more reliable clocks.

**Comment by rocky** [comment]
I think the technical aspect of this has been resolved. What remains is either a revision of the implementation or a dispute over whether this should be tracked. 

I think it best to close this and open another issue is needed for the implementation part.
